"""new field in user model

Revision ID: 675dcf9b3dad
Revises: 2a2198115949
Create Date: 2020-12-01 10:37:41.374786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675dcf9b3dad'
down_revision = '2a2198115949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
